# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
