# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='posted',
            field=models.DateField(auto_now=True),
        ),
    ]
